vimrc: remove CFLAGS=-w from makeprg
…it changes the error messages from:

src/main.o: In function `xcb_check_cb':
/home/michael/i3/../i3/src/main.c:117: undefined reference to `uiae'
collect2: error: ld returned 1 exit status

to:

src/main.o: In function `xcb_check_cb':
main.c:(.text+0x70): undefined reference to `uiae'
collect2: error: ld returned 1 exit status

…which breaks NeoMake.